[[constraint]]
  name = "github.com/go-openapi/errors"
  version = "0.19.2"

[[constraint]]
  name = "github.com/go-openapi/loads"
  version = "0.19.2"

[[constraint]]
  name = "github.com/go-openapi/runtime"
  version = "0.19.4"

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "0.19.2"

[[constraint]]
  name = "github.com/go-openapi/strfmt"
  version = "0.19.2"

[[constraint]]
  name = "github.com/go-openapi/swag"
  version = "0.19.5"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[metadata.heroku]
root-package = "github.com/wunari/easypoll-backend"
